apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankapp
      version: green
  template:
    metadata:
      labels:
        app: bankapp
        version: green
    spec:
      containers:
      - name: bankapp
        image: dockerhub_username/bankapp:green
        ports:
        - containerPort: 8080
