apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
spec:
  type: NodePort              # NodePort so you can access from host
  selector:
    app: bankapp
  ports:
    - protocol: TCP
      port: 8080              # service port
      targetPort: 8080        # container port
      nodePort: 30080         # fixed NodePort (optional) - can be in range 30000-32767
